/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";


export default function Avocado(props) {
  const { nodes, materials } = useGLTF(
    "/avocado/food_avocado_01_4k.gltf"
  );
  return (
    <group {...props} dispose={null} scale={100}>
      <mesh
        geometry={nodes.food_avocado_01.geometry}
        material={materials.food_avocado_01}
      />
    </group>
  );
}

useGLTF.preload("/avocado/food_avocado_01_4k.gltf");
