/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";


export default function Lime(props) {
  const { nodes, materials } = useGLTF(
    "/lime/food_lime_01_4k.gltf"
  );
  return (
    <group {...props} dispose={null} scale={100}>
      <mesh
        geometry={nodes.food_lime_01.geometry}
        material={materials.lime_apple_01}
      />
    </group>
  );
}

useGLTF.preload("/lime/food_lime_01_4k.gltf");
