/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";


export default function Pomegranate(props) {
  const { nodes, materials } = useGLTF(
    "/pomegranate/food_pomegranate_01_4k.gltf"
  );
  return (
    <group {...props} dispose={null} scale={100}>
      <mesh
        geometry={nodes.food_pomegranate_01.geometry}
        material={materials.food_pomegranate_01}
      />
    </group>
  );
}

useGLTF.preload("/apple/food_pomegranate_01_4k.gltf");
